# Generated by Django 4.2.5 on 2023-10-05 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(help_text='Автор объявления', on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(help_text='Укажите текст объявления', verbose_name='Текст'),
        ),
    ]
