# Generated by Django 4.2.5 on 2023-10-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_options_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=None, help_text='Укажите текст объявления', max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
