# Generated by Django 4.2.5 on 2023-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Заголовок объявления', max_length=255, verbose_name='Заголовок'),
        ),
    ]
